config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('retail.urls', namespace='retail')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retail/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from retail.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ContactPageView, InfoPageView, HomeView
from retail.apps import RetailConfig

app_name = RetailConfig.name
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    # метод для отображения отдельной страницы с товаром (по одному товару)
    path('retail/contact/', ContactPageView.as_view(), name='contact'),
    path('retail/info/', InfoPageView.as_view(), name='info'),
    # В декоратор кеширования cache_page передается время его жизни (60 сек) и ссылка на контроллер (contact).
    # Это позволяет кешировать весь контроллер
    path('retail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('retail/list/', ProductListView.as_view(), name='product_list'),
    path('retail/create/', ProductCreateView.as_view(), name='product_create'),
    path('retail/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('retail/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_confirm_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, logout_view

app_name = UsersConfig.name
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
]

retail/models.py
from django.db import models
from users.models import User

NULLABLE = {'blank': True, 'null': True}  # форма, если параметр необязателен


class Contacts(models.Model):
    email = models.EmailField(max_length=100, verbose_name='Email', help_text="Введите имэйл")
    country = models.CharField(max_length=50, verbose_name="Страна")
    city = models.CharField(max_length=50, verbose_name="Город")
    street = models.CharField(max_length=50, verbose_name="Улица")
    house_number = models.IntegerField(verbose_name="№ дома")

    def __str__(self):
        return f"{self.country} {self.city} {self.street} {self.house_number}"

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование продукта', help_text="Введите продукт")
    description = models.CharField(max_length=1000, verbose_name='Описание', help_text="Введите описание продукта",
                                   **NULLABLE)
    model = models.CharField(max_length=1000, verbose_name='Модель', help_text="Введите модель продукта", **NULLABLE)
    photo = models.ImageField(upload_to='retail/photo', verbose_name="Фото продукта", **NULLABLE)
    price = models.IntegerField(verbose_name='Цена', help_text="Введите цену продукта")
    manufactured_at = models.DateField(**NULLABLE, verbose_name='Дата выхода продукта на рынок',
                                       help_text="Введите дату выхода продукта на рынок")

    def __str__(self):
        return f'{self.name}: {self.description}. Модель:{self.model}. Цена: {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name', 'description', 'model', 'price']
        # Поля для функционала прав доступа - варианты редактирования
        # permissions = [
        #     ('cancel_publication', 'Can cancel publication'),
        #     ('edit_description', 'Can edit description'),
        #     ('change_category', 'Can change category'),
        # ]


class Factory(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название завода', help_text="Введите название завода")
    contact = models.ForeignKey(Contacts, verbose_name='Контакт завода', help_text='Укажите контакт завода', **NULLABLE,
                                on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, verbose_name='Продукт', help_text='Укажите продукт', **NULLABLE,
                                on_delete=models.SET_NULL)
    debt = models.DecimalField(verbose_name='Долг перед поставщиком', help_text='Укажите долг перед поставщиком',
                               max_digits=10, decimal_places=2)
    created_at = models.DateField(**NULLABLE, verbose_name='Дата создания записи в БД', auto_now_add=True)

    def __str__(self):
        return f"{self.name} {self.contact}"

    class Meta:
        verbose_name = "Завод"
        verbose_name_plural = "Заводы"


class RetailNetwork(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название розничной сети', help_text="Введите розничную сеть")
    contact = models.ForeignKey(Contacts, verbose_name='Контакт розничной сети',
                                help_text='Укажите контакт розничной сети', **NULLABLE, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, verbose_name='Продукт', help_text='Укажите продукт', **NULLABLE,
                                on_delete=models.SET_NULL)
    factory_supplier = models.ForeignKey(Factory, verbose_name='Завод-поставщик', help_text='Укажите завод-поставщик',
                                         **NULLABLE, on_delete=models.SET_NULL)
    debt = models.DecimalField(verbose_name='Долг перед поставщиком', help_text='Укажите долг перед поставщиком',
                               max_digits=10, decimal_places=2, **NULLABLE)
    created_at = models.DateField(**NULLABLE, verbose_name='Дата создания записи в БД', auto_now_add=True)

    def __str__(self):
        return f"{self.name} {self.contact}"

    class Meta:
        verbose_name = "Розничная сеть"
        verbose_name_plural = "Розничные сети"


class IP(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование ИП', help_text="Введите наименование ИП")
    contact = models.ForeignKey(Contacts, verbose_name='Контакт ИП', help_text='Укажите Контакт ИП', **NULLABLE,
                                on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, verbose_name='Продукт', help_text='Укажите продукт', **NULLABLE,
                                on_delete=models.SET_NULL)
    factory_supplier = models.ForeignKey(Factory, verbose_name='Завод-поставщик', help_text='Укажите завод-поставщик',
                                         **NULLABLE, on_delete=models.SET_NULL)
    retail_network_supplier = models.ForeignKey(RetailNetwork, verbose_name='Розничная сеть-поставщик',
                                                help_text='Укажите розничную сеть-поставщик', **NULLABLE,
                                                on_delete=models.SET_NULL)
    debt = models.DecimalField(verbose_name='Долг перед поставщиком', help_text='Укажите долг перед поставщиком',
                               max_digits=10, decimal_places=2, **NULLABLE)
    created_at = models.DateField(**NULLABLE, verbose_name='Дата создания записи в БД', auto_now_add=True)

    def __str__(self):
        return f"{self.name} {self.contact}"

    class Meta:
        verbose_name = "ИП"
        verbose_name_plural = "Ипешечки"

retail/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField, DateTimeInput
from retail.models import Product


class StyleFormMixin:
    """Стилизация для формы"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        # Строка для исключения поля. Если нужно вывести все - пишем "__all__"
        exclude = ("views_counter", 'owner')
        # widgets = {
        #     'datetime_booking': DateTimeInput(
        #         format='%Y-%m-%dT%H:%M',  # формат для datetime-local
        #         attrs={'class': 'form-control',
        #                'placeholder': 'Select a date and time',
        #                'type': 'datetime-local'
        #                }),
        # }

    # def clean_datetime_booking(self):
    #     datetime_booking = self.cleaned_data['datetime_booking']
    #     booking_time = datetime_booking.time()
    #     # Проверяем, что часы в диапазоне от 12 до 23
    #     if not (12 <= booking_time.hour <= 23):
    #         raise ValidationError("Выберите время с 12:00 до 23:00.")
    #     # Проверяем, что минуты равны 00, 15, 30 или 45
    #     if booking_time.minute not in {0, 15, 30, 45}:
    #         raise ValidationError("Минуты должны быть 00, 15, 30 или 45.")
    #     return datetime_booking

    forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция",
                       "радар"]

    # def clean_availability_check(self):
    #     date_to_check = self.cleaned_data['datetime_booking']
    #     exists = Booking.objects.filter(datetime_booking=date_to_check).exists()
    #     if exists:
    #         raise ValidationError("Данная дата уже существует в базе данных.")

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for forbidden_word in self.forbidden_words:
            if forbidden_word in cleaned_data.lower():
                raise ValidationError(f'Наименование не должно содержать слово "{forbidden_word}"')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for forbidden_word in self.forbidden_words:
            if forbidden_word in cleaned_data.lower():
                raise ValidationError(f'Описание не должно содержать слово "{forbidden_word}"')
        return cleaned_data


class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        # Строка для исключения поля. Если нужно вывести все - пишем "__all__"
        fields = ("description",)

retail/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied, ValidationError
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.functional import SimpleLazyObject
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from config.settings import EMAIL_HOST_USER
from retail.forms import ProductForm, ProductModeratorForm
from retail.models import Product
from users.models import User


class HomeView(TemplateView):
    """Класс, отображающий базовую страницу"""
    template_name = 'retail/index.html'


class ProductListView(LoginRequiredMixin, ListView):
    """Класс, заменяющий функцию product_list (FBV на CBV)"""
    model = Product
    template_name = 'retail/product_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Product.objects.all()
        else:
            return Product.objects.filter(owner=self.request.user)


class ProductDetailView(DetailView):
    """Класс, заменяющий функцию product_detail (FBV на CBV)"""
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('retail:product_list')

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse('retail:product_list')
        else:
            return reverse('retail:index')

    # def form_valid(self, form):
    #     """Метод для """
    #     ...


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    # template_name = 'retail/product_create.html'
    success_url = reverse_lazy('retail:product_list')

    def get_success_url(self):
        return reverse('retail:product_detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        """Метод для работы с правами доступа"""
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm('product.can_cancel_publication') and user.has_perm(
                'product.can_edit_description') and user.has_perm('product.can_change_category'):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'retail/product_confirm_delete.html'
    success_url = reverse_lazy('retail:product_list')


class ContactPageView(TemplateView):
    """Класс для отображения страницы с контактами"""
    template_name = 'retail/contact.html'

    def post(self, request, *args, **kwargs):
        """Метод для приема инфы с фронтэнда в контактах и ее вывода в консоль"""
        if request.method == 'POST':
            name = request.POST.get('name')
            email = request.POST.get('email')
            message = request.POST.get('message')
            print(f'{name} ({email}): {message}')
        return render(request, 'retail/contact.html')

    def get(self, request):
        return render(request, 'retail/contact.html')


class InfoPageView(TemplateView):
    """Класс для отображения страницы с информацией о ресторане"""
    template_name = 'retail/info.html'

    def get(self, request):
        return render(request, 'retail/info.html')

retail/templates/retail/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'retail/includes/inc_menu.html' %}
</header>

<main>
    {% block content%}
    {% endblock%}
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1"> Эта страница создана потом и продом. </p>
        <p class="mb-0"> 2024 </p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

retail/templates/retail/contact.html
{% extends 'retail/base.html' %}
{% load static %}
{% block content %}
<div class="col-md-6 text-center container">
    <div class="card mb-4 box-shadow text-center">
        <div class="card-body">
            <p class="card-text">
                Мы в облаке
            </p>
        </div>
        <div class="btn-group">
            <a class="btn btn-primary" href="{% url 'retail:index' %}"
               role="button">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

retail/templates/retail/index.html
{% extends 'retail/base.html' %}
{% load static %}
{% block content %}
<section class="py-5 text-center container">
    <img src="{% static 'images/electro1.jpg' %}" class="d-block w-100" alt="Photo">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light"> ЭЛЕКТРОСЕТЬ </h1>
            <p class="lead text-body-secondary">ПРОДАЕМ ЭЛЕКТРОНИКУ</p>
            <p class="lead text-body-secondary">вставляй свой штепсель - и погнали</p>
            <p>
                <a class="btn btn-primary" href="{% url 'retail:product_create' %}"
                   role="button">Создать продукт</a>
            </p>
            <p>
                <a class="btn btn-primary" href="{% url 'retail:product_list' %}"
                   role="button">Все продукты</a>
            </p>
        </div>
    </div>
</section>
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light"> НУЖНА ЭЛЕКТРОНИКА? ТЫ ПО АДРЕСУ </h1>
            <p class="lead text-body-secondary">ВСЕ ОТ ПОСТАВЩИКОВ</p>
            <p class="lead text-body-secondary">СОВЕТСКИЕ ЦЕНЫ</p>
            <p class="lead text-body-secondary">У НАС ЗАКУПАЮТСЯ ДЕПУТАТЫ</p>
        </div>
    </div>
</section>
{% endblock %}

retail/templates/retail/info.html
{% extends 'retail/base.html' %}
{% load static %}
{% block content %}
<div class="col-md-6 text-center container">
    <img src="{% static 'images/electro2.jpg' %}" class="d-block w-100" alt="Photo">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
            <h2>САМАЯ ЗНОЙНАЯ СЕТЬ ПО ПРОДАЖЕ ЭЛЕКТРОНИКИ.</h2>
            <h6>Наши ценности: убийственный прайс, стильный выбор.</h6>
            </div>
        <div class="btn-group">
            <a class="btn btn-primary" href="{% url 'retail:index' %}"
               role="button">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

retail/templates/retail/product_confirm_delete.html
{% extends 'retail/base.html' %}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Точно удаляем {{ object.name }} ?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-danger">
                        Удалить
                    </button>
                    <a class="btn btn-primary" href="{% url 'retail:product_list' %}"
                       role="button">Отменить удаление</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

retail/templates/retail/product_list.html
{% extends 'retail/base.html' %}
{% load my_tags %}
<!--Подключаем файл my_tags, чтобы можно было выводить фото -->
{% block content%}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in object_list %}
            <!-- Цикл, с помощью которого мы отображаем столько карточек с товарами, сколько имеем товаров в базе-->
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ product.photo|media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ product.name }}</p>
                        <p class="card-text">Цена: {{ product.price }} руб.</p>
                        <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                        <!--Этой строкой для единообразия выводимых карточек отображаемое описание ограничивается 100 символами.-->
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if perms.product.can_cancel_publication and perms.product.can_edit_description and perms.product.can_change_category or user == product.owner or user == is_superuser %}
                                    <a class="btn btn-warning" href="{% url 'retail:product_update' product.pk %}" role="button">Редактировать</a>
                                {% endif %}
                                <a class="btn btn-primary" href="{% url 'retail:product_detail' product.pk %}" role="button">Посмотреть</a>
                                {% if perms.product.can_cancel_publication and perms.product.can_edit_description and perms.product.can_change_category or user == product.owner %}
                                    <a class="btn btn-danger" href="{% url 'retail:product_confirm_delete' product.pk %}" role="button">Удалить</a>
                                {% endif %}
                            </div>
                            <small class="text-body-secondary">При покупке даем путевку в КНДР</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock%}